# Generated by Django 2.2 on 2019-04-30 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dt_nascimento', models.DateField()),
                ('vivo', models.BooleanField(default=True)),
                ('nacionalidade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('genero', models.CharField(choices=[('av', 'Aventura'), ('rm', 'Romance'), ('bg', 'Biografia'), ('sf', 'Scifi'), ('tr', 'Terror'), ('aa', 'Autoajuda'), ('mg', 'Manga'), ('rl', 'Religioso'), ('hq', 'HQ')], max_length=2)),
                ('dt_lancamento', models.DateField()),
                ('descricao', models.TextField(default='')),
                ('editora', models.CharField(default='', max_length=20)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('qtd_paginas', models.IntegerField()),
                ('edicoes', models.IntegerField()),
                ('nome', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='app.Autor')),
            ],
        ),
    ]
